# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: 
first_name: Anthony
middle_name: C.
last_name: NDUKA
email: #
description: > 
  Hi, it's Toneey here, and this is my academic portfolio.
  You can find more about what I’m up to and what I find interesting.
footer_text: >
keywords: tony, nduka, anthony, tech-blog, data-science, health-tech, hcc, human-computer-interactions
lang: en
icon: logo/alt-logo.png

url: "https://temela.github.io"
baseurl: ""

last_updated: true
impressum_path:

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: false
search_enabled: true
socials_in_search: true
max_width: 800px

serve_og_meta: true
serve_schema_org: true
og_image: /assets/img/logo/l.png

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: temela
x_username: _tchiemela
linkedin_username: tchiemela
orcid_id: 
kaggle_id: 
contact_note: > Reach me via tchiemela@gmail.com

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics:
cronitor_analytics:
google_site_verification:
bing_site_verification:

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Blogger's pen
blog_description: Here we are!
permalink: /blog/:year/:title/

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 3

giscus:
  repo: asboyer/asboyer.github.io
  category: Comments
  mapping: title
  strict: 1
  reactions_enabled: 0
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  notes:
    defaults:
      layout: post
    output: true
    permalink: /notes/:path/
  favs:
    defaults:
      layout: post
    output: true
    permalink: /favs/:categories/:path/

announcements:
  enabled: true
  scrollable: false
  limit: 3

latest_posts:
  enabled: true
  scrollable: false
  limit: 3

key_projects:
  enabled: true
  scrollable: false
  limit: 3

latest_notes:
  enabled: true
  scrollable: false
  limit: 8

latest_favs:
  enabled: true
  scrollable: false
  limit: 3

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages"]
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

jekyll-minifier:
  exclude: ["robots.txt", "assets/js/search/*.js"]
  uglifier_args:
    harmony: true

jekyll-archives:
  enabled: [year, tags, categories]
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
    category: "/blog/category/:name/"

display_tags: ["code", "sierra-escape"]
display_categories: ["essays", "projects"]
display_authors: ["Andrew Boyer"]
all_authors: ["andrew-boyer"]

scholar:
  last_name: [Einstein]
  first_name: [Albert, A.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

enable_publication_badges:
  altmetric: true
  dimensions: true

filtered_bibtex_keywords:
  [abbr, abstract, altmetric, arxiv, bibtex_show, blog, code, html, pdf, poster, preview, selected, slides, supp, video, website]

max_author_limit: 3
more_authors_animation_delay: 10
enable_publication_thumbnails: true

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".gif"
  output_formats:
    webp: "-quality 85"

enable_google_analytics: true
enable_cronitor_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: true
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true

bootstrap-table:
  version: "1.22.1"
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
mathjax:
  version: "3.2.0"
masonry:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
medium_zoom:
  version: "1.0.8"
  integrity: "sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8="

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json
jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
