source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-scholar"
gem "jekyll-paginate-v2"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-get-json"
gem "jekyll-toc"
gem "jemoji"
gem "jekyll-twitter-plugin"
gem "jekyll-minifier"
gem "kramdown-parser-gfm"
gem "bundler", "~> 2.6"
