name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.158.0
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get install -y libxml2-dev libxslt1-dev
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy
        uses: actions/deploy-pages@v3.0.1
        id: deployment
